<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('ratesvalid', function (Blueprint $table) {
            $table->integer('id');
            $table->integer('id_hotel')->nullable();
            $table->string('fecha_ini', 50)->nullable();
            $table->string('fecha_fin', 50)->nullable();
            $table->double('sgl', 10, 2);
            $table->double('dbl', 10, 2);
            $table->double('tpl', 10, 2);
            $table->double('qua', 10, 2);
            $table->double('sgl2', 10, 2);
            $table->double('dbl2', 10, 2);
            $table->double('tpl2', 10, 2);
            $table->double('qua2', 10, 2);
            $table->double('sgl3', 10, 2);
            $table->double('dbl3', 10, 2);
            $table->double('tpl3', 10, 2);
            $table->double('qua3', 10, 2);
            $table->double('sgl4', 10, 2);
            $table->double('dbl4', 10, 2);
            $table->double('tpl4', 10, 2);
            $table->double('qua4', 10, 2);
            $table->double('sgl5', 10, 2);
            $table->double('dbl5', 10, 2);
            $table->double('tpl5', 10, 2);
            $table->double('qua5', 10, 2);
            $table->double('sgl6', 10, 2);
            $table->double('dbl6', 10, 2);
            $table->double('tpl6', 10, 2);
            $table->double('qua6', 10, 2);
            $table->double('sgl7', 10, 2);
            $table->double('dbl7', 10, 2);
            $table->double('tpl7', 10, 2);
            $table->double('qua7', 10, 2);
            $table->double('sgl8', 10, 2);
            $table->double('dbl8', 10, 2);
            $table->double('tpl8', 10, 2);
            $table->double('qua8', 10, 2);
            $table->double('sglm', 10, 2);
            $table->double('dblm', 10, 2);
            $table->double('tplm', 10, 2);
            $table->double('quam', 10, 2);
            $table->double('sglm2', 10, 2);
            $table->double('dblm2', 10, 2);
            $table->double('tplm2', 10, 2);
            $table->double('quam2', 10, 2);
            $table->double('sglm3', 10, 2);
            $table->double('dblm3', 10, 2);
            $table->double('tplm3', 10, 2);
            $table->double('quam3', 10, 2);
            $table->double('sglm4', 10, 2);
            $table->double('dblm4', 10, 2);
            $table->double('tplm4', 10, 2);
            $table->double('quam4', 10, 2);
            $table->double('sglm5', 10, 2);
            $table->double('dblm5', 10, 2);
            $table->double('tplm5', 10, 2);
            $table->double('quam5', 10, 2);
            $table->double('sglm6', 10, 2);
            $table->double('dblm6', 10, 2);
            $table->double('tplm6', 10, 2);
            $table->double('quam6', 10, 2);
            $table->double('sglm7', 10, 2);
            $table->double('dblm7', 10, 2);
            $table->double('tplm7', 10, 2);
            $table->double('quam7', 10, 2);
            $table->double('sglm8', 10, 2);
            $table->double('dblm8', 10, 2);
            $table->double('tplm8', 10, 2);
            $table->double('quam8', 10, 2);
            $table->double('sgld', 10, 2);
            $table->double('dbld', 10, 2);
            $table->double('tpld', 10, 2);
            $table->double('quad', 10, 2);
            $table->double('sgld2', 10, 2);
            $table->double('dbld2', 10, 2);
            $table->double('tpld2', 10, 2);
            $table->double('quad2', 10, 2);
            $table->double('sgld3', 10, 2);
            $table->double('dbld3', 10, 2);
            $table->double('tpld3', 10, 2);
            $table->double('quad3', 10, 2);
            $table->double('sgld4', 10, 2);
            $table->double('dbld4', 10, 2);
            $table->double('tpld4', 10, 2);
            $table->double('quad4', 10, 2);
            $table->double('sgld5', 10, 2);
            $table->double('dbld5', 10, 2);
            $table->double('tpld5', 10, 2);
            $table->double('quad5', 10, 2);
            $table->double('sgld6', 10, 2);
            $table->double('dbld6', 10, 2);
            $table->double('tpld6', 10, 2);
            $table->double('quad6', 10, 2);
            $table->double('sgld7', 10, 2);
            $table->double('dbld7', 10, 2);
            $table->double('tpld7', 10, 2);
            $table->double('quad7', 10, 2);
            $table->double('sgld8', 10, 2);
            $table->double('dbld8', 10, 2);
            $table->double('tpld8', 10, 2);
            $table->double('quad8', 10, 2);
            $table->double('chv21', 10, 2);
            $table->double('chm21', 10, 2);
            $table->double('chd21', 10, 2);
            $table->double('chv32', 10, 2);
            $table->double('chm32', 10, 2);
            $table->double('chd32', 10, 2);
            $table->double('chv43', 10, 2);
            $table->double('chm43', 10, 2);
            $table->double('chd43', 10, 2);
            $table->double('chv54', 10, 2);
            $table->double('chm54', 10, 2);
            $table->double('chd54', 10, 2);
            $table->double('chv65', 10, 2);
            $table->double('chm65', 10, 2);
            $table->double('chd65', 10, 2);
            $table->double('chv76', 10, 2);
            $table->double('chm76', 10, 2);
            $table->double('chd76', 10, 2);
            $table->double('chv87', 10, 2);
            $table->double('chm87', 10, 2);
            $table->double('chd87', 10, 2);
            $table->double('chv98', 10, 2);
            $table->double('chm98', 10, 2);
            $table->double('chd98', 10, 2);
            $table->double('resortprice', 10, 2)->nullable();
            $table->double('brackfast', 10, 2)->nullable();
            $table->integer('type_rate')->default(0);
            $table->integer('id_agency')->default(-1);
            $table->text('company_name')->nullable();
            $table->string('rate', 50)->nullable();
            $table->integer('rate_no')->default(0);
            $table->double('fdv_adult21', 10, 2);
            $table->double('fdv_child21', 10, 2);
            $table->double('fdm_adult21', 10, 2);
            $table->double('fdm_child21', 10, 2);
            $table->double('fdd_adult21', 10, 2);
            $table->double('fdd_child21', 10, 2);
            $table->double('fdv_adult32', 10, 2);
            $table->double('fdv_child32', 10, 2);
            $table->double('fdm_adult32', 10, 2);
            $table->double('fdm_child32', 10, 2);
            $table->double('fdd_adult32', 10, 2);
            $table->double('fdd_child32', 10, 2);
            $table->double('fdv_adult43', 10, 2);
            $table->double('fdv_child43', 10, 2);
            $table->double('fdm_adult43', 10, 2);
            $table->double('fdm_child43', 10, 2);
            $table->double('fdd_adult43', 10, 2);
            $table->double('fdd_child43', 10, 2);
            $table->double('fdv_adult54', 10, 2);
            $table->double('fdv_child54', 10, 2);
            $table->double('fdm_adult54', 10, 2);
            $table->double('fdm_child54', 10, 2);
            $table->double('fdd_adult54', 10, 2);
            $table->double('fdd_child54', 10, 2);
            $table->double('fdv_adult65', 10, 2);
            $table->double('fdv_child65', 10, 2);
            $table->double('fdm_adult65', 10, 2);
            $table->double('fdm_child65', 10, 2);
            $table->double('fdd_adult65', 10, 2);
            $table->double('fdd_child65', 10, 2);
            $table->double('fdv_adult76', 10, 2);
            $table->double('fdv_child76', 10, 2);
            $table->double('fdm_adult76', 10, 2);
            $table->double('fdm_child76', 10, 2);
            $table->double('fdd_adult76', 10, 2);
            $table->double('fdd_child76', 10, 2);
            $table->double('fdv_adult87', 10, 2);
            $table->double('fdv_child87', 10, 2);
            $table->double('fdm_adult87', 10, 2);
            $table->double('fdm_child87', 10, 2);
            $table->double('fdd_adult87', 10, 2);
            $table->double('fdd_child87', 10, 2);
            $table->double('fdv_adult98', 10, 2);
            $table->double('fdv_child98', 10, 2);
            $table->double('fdm_adult98', 10, 2);
            $table->double('fdm_child98', 10, 2);
            $table->double('fdd_adult98', 10, 2);
            $table->double('fdd_child98', 10, 2);
            $table->double('trip100', 10, 2);
            $table->double('trip200', 10, 2);
            $table->double('trip300', 10, 2);
            $table->double('trip101', 10, 2);
            $table->double('trip201', 10, 2);
            $table->double('trip301', 10, 2);
            $table->double('trip100c', 10, 2);
            $table->double('trip200c', 10, 2);
            $table->double('trip300c', 10, 2);
            $table->double('trip101c', 10, 2);
            $table->double('trip201c', 10, 2);
            $table->double('trip301c', 10, 2);
            $table->double('t_in', 10, 2);
            $table->double('t_out', 10, 2);
            $table->double('car_in', 10, 2);
            $table->double('car_out', 10, 2);
            $table->double('schv', 10, 2);
            $table->double('schm', 10, 2);
            $table->double('schd', 10, 2);
            $table->double('schv2', 10, 2);
            $table->double('schm2', 10, 2);
            $table->double('schd2', 10, 2);
            $table->double('schv3', 10, 2);
            $table->double('schm3', 10, 2);
            $table->double('schd3', 10, 2);
            $table->double('schv4', 10, 2);
            $table->double('schm4', 10, 2);
            $table->double('schd4', 10, 2);
            $table->string('dupli', 11);
            $table->string('fecha_schv', 20)->nullable();
            $table->string('fecha_schm', 20)->nullable();
            $table->string('fecha_schv2', 20)->nullable();
            $table->string('fecha_schm2', 20)->nullable();
            $table->string('fecha_schv3', 20)->nullable();
            $table->string('fecha_schm3', 20)->nullable();
            $table->string('fecha_schv4', 20)->nullable();
            $table->string('fecha_schm4', 20)->nullable();
            $table->double('pax1v_21', 10, 2);
            $table->double('pax2v_21', 10, 2);
            $table->double('pax1m_21', 10, 2);
            $table->double('pax2m_21', 10, 2);
            $table->double('pax1d_21', 10, 2);
            $table->double('pax2d_21', 10, 2);
            $table->double('pax1v_32', 10, 2);
            $table->double('pax2v_32', 10, 2);
            $table->double('pax1m_32', 10, 2);
            $table->double('pax2m_32', 10, 2);
            $table->double('pax1d_32', 10, 2);
            $table->double('pax2d_32', 10, 2);
            $table->double('pax1v_43', 10, 2);
            $table->double('pax2v_43', 10, 2);
            $table->double('pax1m_43', 10, 2);
            $table->double('pax2m_43', 10, 2);
            $table->double('pax1d_43', 10, 2);
            $table->double('pax2d_43', 10, 2);
            $table->double('pax1v_54', 10, 2);
            $table->double('pax2v_54', 10, 2);
            $table->double('pax1m_54', 10, 2);
            $table->double('pax2m_54', 10, 2);
            $table->double('pax1d_54', 10, 2);
            $table->double('pax2d_54', 10, 2);
            $table->double('pax1v_65', 10, 2);
            $table->double('pax2v_65', 10, 2);
            $table->double('pax1m_65', 10, 2);
            $table->double('pax2m_65', 10, 2);
            $table->double('pax1d_65', 10, 2);
            $table->double('pax2d_65', 10, 2);
            $table->double('pax1v_76', 10, 2);
            $table->double('pax2v_76', 10, 2);
            $table->double('pax1m_76', 10, 2);
            $table->double('pax2m_76', 10, 2);
            $table->double('pax1d_76', 10, 2);
            $table->double('pax2d_76', 10, 2);
            $table->double('pax1v_87', 10, 2);
            $table->double('pax2v_87', 10, 2);
            $table->double('pax1m_87', 10, 2);
            $table->double('pax2m_87', 10, 2);
            $table->double('pax1d_87', 10, 2);
            $table->double('pax2d_87', 10, 2);
            $table->double('pax1v_98', 10, 2);
            $table->double('pax2v_98', 10, 2);
            $table->double('pax1m_98', 10, 2);
            $table->double('pax2m_98', 10, 2);
            $table->double('pax1d_98', 10, 2);
            $table->double('pax2d_98', 10, 2);
        });
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('ratesvalid');
    }
};
